// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
import EditToggleController from "./edit_toggle_controller"
application.register("hello", HelloController)
application.register("edit-toggle", EditToggleController)
import TagPickerController from "./tag_picker_controller"
application.register("tag-picker", TagPickerController)
import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)
